# Generated by Django 3.2.4 on 2021-08-17 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210817_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 19, 8, 30, 184407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='about_me',
            field=models.TextField(blank=True, max_length=512, verbose_name='о себе'),
        ),
    ]
